ssh-config:
  key-path: key-path
configurations:
  kubectl:
    - ssh-client-user-name: ssh-client-user-name
      ssh-client-host-name: ssh-client-host-name
      origin-server: target-machine:target-port
      name: c1-ctt
