kubectl:
  path: kubectl-path
  supported-subcommands:
    - create
  tunnel-configurations:
    - ssh-tunnel-server: linuxserver.io@localhost:2222
      origin-server: 192.168.68.109:64331 
      name: kind-ctt
ssh-config:
  key-path: path/id_rsa